### ISSUE TITLE
DCM can't read device name in iOS 16

### ISSUE THREAD

**Issue by Barbelle11** [versx/DeviceConfigManager#104]
**Device connects to DCM as "iPhone"**
A device with the name "DeviceXX" connects to DCM and becomes "iPhone." RDM creates a matching "iPhone" entry in RDM-db. I've tried this with 4 different phones and the behavior is consistent. DCM does not allow me to edit the name.

**To Reproduce**
Add new device to DCM when device has iOS 16.x
(Using redux with config set to correct DCM url)

**Expected behavior**
The device was prepared with AC2 including name. Name is identified in mobile.provision from Apple. Device name appears on desktop and in AC2. Those steps usually result in the device connecting with DCM and keeping its designated name, which is then passed off to RDM. I expected that I could edit the device's name in DCM, but that is not a function. (Could it be? That might be the easiest fix.)

**Desktop**
 - OS: Ventura 13.2.1
 - Browser: Firefox 
 - Version: 112.0.1

**Smartphone**
 - Device: iPhone SE, 2nd gen
 - OS: 16.4
 - Private Wi-Fi address is turned off
 - Developer Mode is turned on (req'd to run app)

**Additional context**
Things I've tried: changing the name of the device in RDM-db and DCM-db (DCM changes the name back to "iPhone" and RDM then shows 2 entries: device name and "iPhone"). Also tried: re-setting device to factory settings, re-loading and re-deploying app, deleting device from DCM, resetting auth key and starting over, stopping DCM and starting over, rebooting computer, and probably a few other things. I also tried taking the devices back to iOS 15.x (without success) because I suspect that security features in iOS 16 are keeping the device from revealing its name to DCM.

I've tested 4 different devices (with iOS 16.x) and the behavior is the same. When I connect two new devices, DCM gives them both the name "iPhone" and treats them as if they're the same device. RDM also sees them as the same device: it serves them identical instructions. Nevertheless, Auth server treats the pair as 2 devices both of which start working in tandem. The end result is that in the current state, I can only add one device: "iPhone". The rest of my "new" devices are unusable.

**Comment by Kneckter** [comment]
Hello there. DCM and RDM are reading data sent to them by the MITM client on the phone, they don't do this query themselves. This issue would need to be corrected in app you're using on the phone that reads the name from the phone before it sends that info to DCM/RDM. The field that's being sent with the name is the `uuid` field that's posted to the DCM/RDM APIs. 

Also, you won't be able to downgrade to iOS 15 because Apple only allows that while the image has a valid signature. Apple has invalidated the signatures on iOS 15 for the SE 2nd gen so you're stuck on iOS 16.

**Comment by Barbelle11** [comment]
MITM is now aware and working to correct it. Thank you for your quick reply!!
