### ISSUE TITLE
isRebootable flag for devices

### ISSUE THREAD

**Issue by tppkgo** [versx/DeviceConfigManager#71]
**Is your feature request related to a problem? Please describe.**
If a device has a faulty/replaced home button a reboot will make it sit until the "touchid inactivated" message is dismissed.
**Describe the solution you'd like**
a flag for each device selecting if it should be rebooted or not. Default may be ON but option to deselect for "broken homebutton" devices.
**Describe alternatives you've considered**
Modding RemoteListener.... But better with a toggle for each device.
**Additional context**
I hope description is clear. I got to many devices with broken homebutton due to the cheap price. Im not using the reboot feature at all right now as so many devices would just sit offline after a reboot.

**Comment by versx** [comment]
Good suggestion, I'll hopefully add it sometime this weekend.
